// Generated by Wrangler on Tue Aug 13 2024 13:43:27 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	BROWSER: DurableObjectNamespace<import("./src/index").Browser>;
	MYBROWSER: Fetcher;
}
