#:schema node_modules/wrangler/config-schema.json
name = "uscf-player-search"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = [ "nodejs_compat"]
account_id = "b29a1c7c732ad77c80e3cb9c33c34a89"

# Browser Rendering API binding
browser = { binding = "MYBROWSER" }

# Binding to a Durable Object
[[durable_objects.bindings]]
name = "BROWSER"
class_name = "Browser"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Browser"] # Array of new classes