#:schema node_modules/wrangler/config-schema.json
name = "uscf-player-search"
main = "src/index.ts"
compatibility_date = "2024-09-02"
compatibility_flags = [ "nodejs_compat"]
account_id = "b29a1c7c732ad77c80e3cb9c33c34a89"